[phases.setup]
nixPkgs = [
    "php82", 
    "php82Extensions.pdo_pgsql",  # <--- CAMBIA pdo_pgsql POR pdo_mysql
    "php82Extensions.redis", 
    "php82Extensions.gd",
    "php82Extensions.zip", 
    "php82Extensions.mbstring", 
    "composer_2",
    "nodejs_20", 
    "npm-10_x"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader",
"npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan storage:link",
  # Las migraciones aquí pueden fallar si la DB no está lista, 
  # pero con el driver correcto deberían pasar.
  "php artisan migrate --force"
]

[start]
# Ojo: Para producción en Railway, es mejor usar el servidor nativo o Frannk
# pero si prefieres artisan serve, este comando está bien.
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"